// /our-clients: every client, past and present, one alphabetical grid.
// Display names are curated from Jon's NEED ART sheet (Oct 2026); slug =
// file name for the tile art in public/marketing/clients/:
//   <slug>.jpg  photo, 1080x1080 square
//   <slug>.png  white logo, transparent, trimmed
// Add art with scripts/import-client-art.mjs (resizes + names it). A client
// with no art yet renders as a name-only tile.

export type Client = { name: string; slug: string };

export const CLIENTS: Client[] = [
  { name: "13TH HEAVEN", slug: "13th-heaven" },
  { name: "Atlas News", slug: "atlas-news" },
  { name: "Baldwin Motorsports", slug: "baldwin-motorsports" },
  { name: "Bartone Bros. Racing", slug: "bartone-bros-racing" },
  { name: "Bauer Precision", slug: "bauer-precision" },
  { name: "Black Canyon Systems", slug: "black-canyon-systems" },
  { name: "Black Rifle Coffee Company", slug: "black-rifle-coffee-company" },
  { name: "Black Triangle", slug: "black-triangle" },
  { name: "Blue Can Training", slug: "blue-can-training" },
  { name: "Bravo Actual", slug: "bravo-actual" },
  { name: "Carryology", slug: "carryology" },
  { name: "Cerberus Operations", slug: "cerberus-operations" },
  { name: "Circa Casino Resort", slug: "circa-casino-resort" },
  { name: "CLEARED HOT", slug: "cleared-hot" },
  { name: "Concordia Defense", slug: "concordia-defense" },
  { name: "Die Free Co", slug: "die-free-co" },
  { name: "Dirty Kid", slug: "dirty-kid" },
  { name: "Disco 32", slug: "disco-32" },
  { name: "Discount Firearms & Ammo", slug: "discount-firearms-and-ammo" },
  { name: "Echelon", slug: "echelon" },
  { name: "FDE Group", slug: "fde-group" },
  { name: "Finance and Maneuver", slug: "finance-and-maneuver" },
  { name: "Firearms Policy Coalition", slug: "firearms-policy-coalition" },
  { name: "Flux Defense", slug: "flux-defense" },
  { name: "Forward Observations Group", slug: "forward-observations-group" },
  { name: "Francis Defense", slug: "francis-defense" },
  { name: "Free Rein Coffee", slug: "free-rein-coffee" },
  { name: "Freedom Trading Co.", slug: "freedom-trading-co" },
  { name: "GBRS Group", slug: "gbrs-group" },
  { name: "Gear Lab", slug: "gear-lab" },
  { name: "Guns.com", slug: "guns-com" },
  { name: "Heat", slug: "heat" },
  { name: "Hunter Constantine", slug: "hunter-constantine" },
  { name: "illicit provisions", slug: "illicit-provisions" },
  { name: "Infinite Armory", slug: "infinite-armory" },
  { name: "iRay USA", slug: "iray-usa" },
  { name: "Jello Sauce", slug: "jello-sauce" },
  { name: "Juicey Media", slug: "juicey-media" },
  { name: "Koo Koo Kangaroo", slug: "koo-koo-kangaroo" },
  { name: "Low Rollers Club", slug: "low-rollers-club" },
  { name: "Man In Tree", slug: "man-in-tree" },
  { name: "MARS", slug: "mars" },
  { name: "Mash Transit", slug: "mash-transit" },
  { name: "Matt Matthews", slug: "matt-matthews" },
  { name: "MEM Industries", slug: "mem-industries" },
  { name: "Mojave Repeater", slug: "mojave-repeater" },
  { name: "NFQ", slug: "nfq" },
  { name: "ninebangerz", slug: "ninebangerz" },
  { name: "Nocpix", slug: "nocpix" },
  { name: "Northern Provisions", slug: "northern-provisions" },
  { name: "Noveske Rifleworks", slug: "noveske-rifleworks" },
  { name: "One7Six", slug: "one7six" },
  { name: "Onward Research", slug: "onward-research" },
  { name: "Overpass Bags", slug: "overpass-bags" },
  { name: "Palmetto State Armory", slug: "palmetto-state-armory" },
  { name: "Piece of Mind Guns", slug: "piece-of-mind-guns" },
  { name: "Players Pins", slug: "players-pins" },
  { name: "Presample Depot", slug: "presample-depot" },
  { name: "Privateer Group", slug: "privateer-group" },
  { name: "Q", slug: "q" },
  { name: "Ranch Dressn", slug: "ranch-dressn" },
  { name: "Red Clover Coffee", slug: "red-clover-coffee" },
  { name: "Room Temp Pizza", slug: "room-temp-pizza" },
  { name: "Sapphire LV", slug: "sapphire-lv" },
  { name: "Second Amendment Foundation", slug: "second-amendment-foundation" },
  { name: "Sike Ops", slug: "sike-ops" },
  { name: "Silencer Co", slug: "silencer-co" },
  { name: "SOG", slug: "sog" },
  { name: "soileater", slug: "soileater" },
  { name: "Southwest Bimmers", slug: "southwest-bimmers" },
  { name: "Spiritus Systems", slug: "spiritus-systems" },
  { name: "Squid", slug: "squid" },
  { name: "Stoic Conditioning", slug: "stoic-conditioning" },
  { name: "Superior Defense", slug: "superior-defense" },
  { name: "Tac Hunt Fish", slug: "tac-hunt-fish" },
  { name: "Tag Firearms", slug: "tag-firearms" },
  { name: "Team Blackshell", slug: "team-blackshell" },
  { name: "Team Room Design", slug: "team-room-design" },
  { name: "Thirteen Systems", slug: "thirteen-systems" },
  { name: "THYF", slug: "thyf" },
  { name: "Tobacco Tactical", slug: "tobacco-tactical" },
  { name: "TOTAL CHAOS Fabrication", slug: "total-chaos-fabrication" },
  { name: "Triarc Systems", slug: "triarc-systems" },
  { name: "Vang Comp", slug: "vang-comp" },
  { name: "VBC Cigars", slug: "vbc-cigars" },
  { name: "Ventura Munitions", slug: "ventura-munitions" },
  { name: "Violentia", slug: "violentia" },
  { name: "Wasteland Kooks", slug: "wasteland-kooks" },
  { name: "Weekend Institute", slug: "weekend-institute" },
  { name: "White Phosphor", slug: "white-phosphor" },
  { name: "Wolf Forty Designs", slug: "wolf-forty-designs" },
  { name: "Wrm Fzy", slug: "wrm-fzy" },
  { name: "You Keep Productions", slug: "you-keep-productions" },
  { name: "Zev Technologies", slug: "zev-technologies" },
];
