import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

// POST /api/jobs/quick-create
// Body: { title, client_id, job_type? }
// Creates a minimal job for quick project creation from Art Studio.
// Job number auto-generated by DB trigger. Phase defaults to "intake".
export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { title, client_id, job_type } = await req.json();
    if (!title?.trim()) return NextResponse.json({ error: "Title required" }, { status: 400 });
    if (!client_id) return NextResponse.json({ error: "client_id required" }, { status: 400 });

    // Default job_type from client if not provided
    let finalJobType = job_type;
    if (!finalJobType) {
      const { data: c } = await supabase.from("clients").select("type, default_terms").eq("id", client_id).single();
      finalJobType = (c as any)?.type || "brand";
    }

    const validTypes = ["corporate", "brand", "artist", "tour", "webstore", "drop_ship"];
    if (!validTypes.includes(finalJobType)) finalJobType = "brand";

    const { data, error } = await supabase.from("jobs").insert({
      title: title.trim(),
      client_id,
      job_type: finalJobType,
      phase: "intake",
      job_number: "", // trigger fills this in
    } as any).select("*").single();

    if (error) return NextResponse.json({ error: error.message }, { status: 500 });
    return NextResponse.json({ job: data });
  } catch (e: any) {
    return NextResponse.json({ error: e.message || "Failed" }, { status: 500 });
  }
}
