// Shared "has HPD seen the latest external activity?" computation for art
// briefs. Lifted from /api/art-briefs/route.ts so the Command Center can
// surface the same Unread state Art Studio uses, without duplicating
// the join logic.
//
// Activity sources merged per role:
//   - art_brief_messages (sender_role)
//   - art_brief_files    (uploader_role)
//   - art_brief_file_comments (sender_role)
//
// "Seen" for HPD = max(HPD's own activity timestamp, hpd_last_seen_at).
// Opening a brief in Art Studio bumps hpd_last_seen_at, so glancing
// counts as seen even without posting a reply.
//
// Note: art_brief_file_comments has RLS enabled with no policies
// (migration 040). Read through the service-role client to match the
// pattern in /api/art-briefs and the portal routes.

import { createClient as createAdmin } from "@supabase/supabase-js";

// supabase param is intentionally typed `any` — callers pass clients
// generated by the project's typed helpers (lib/supabase/server,
// lib/supabase/client) with project-specific generics that don't
// match the SDK's bare SupabaseClient signature.
function commentsAdmin(): any {
  return createAdmin(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );
}

type BriefRow = { id: string; hpd_last_seen_at?: string | null };

export type BriefUnreadFields = {
  has_unread_external: boolean;
  unread_by_role: "client" | "designer" | null;
  unread_at: string | null;
};

export async function attachUnreadStatus<T extends BriefRow>(
  briefs: T[],
  supabase: any,
): Promise<(T & BriefUnreadFields)[]> {
  if (briefs.length === 0) return briefs as (T & BriefUnreadFields)[];

  const ids = briefs.map(b => b.id);

  const [msgsRes, filesRes, commentsRes] = await Promise.all([
    supabase.from("art_brief_messages").select("brief_id, sender_role, created_at").in("brief_id", ids),
    supabase.from("art_brief_files").select("brief_id, uploader_role, created_at").in("brief_id", ids),
    commentsAdmin().from("art_brief_file_comments").select("brief_id, sender_role, created_at").in("brief_id", ids),
  ]);

  // Most recent activity timestamp per (brief, role).
  const lastByRole: Record<string, { client?: string; designer?: string; hpd?: string }> = {};
  const bump = (bid: string, role: string | null | undefined, at: string) => {
    const r = role === "client" ? "client" : role === "designer" ? "designer" : "hpd";
    const slot = (lastByRole[bid] ||= {});
    if (!slot[r] || at > slot[r]!) slot[r] = at;
  };

  for (const m of ((msgsRes.data || []) as any[])) bump(m.brief_id, m.sender_role, m.created_at);
  for (const f of ((filesRes.data || []) as any[])) bump(f.brief_id, f.uploader_role, f.created_at);
  for (const c of ((commentsRes.data || []) as any[])) bump(c.brief_id, c.sender_role, c.created_at);

  return briefs.map(b => {
    const la = lastByRole[b.id] || {};
    const clientAt = la.client || "";
    const designerAt = la.designer || "";
    const hpdActivityAt = la.hpd || "";
    const hpdSeenAt = b.hpd_last_seen_at || "";
    const hpdAt = hpdActivityAt > hpdSeenAt ? hpdActivityAt : hpdSeenAt;
    const latestExternal = clientAt > designerAt ? clientAt : designerAt;
    const latestExternalRole: "client" | "designer" = clientAt > designerAt ? "client" : "designer";
    const has_unread_external = !!latestExternal && latestExternal > hpdAt;
    return {
      ...b,
      has_unread_external,
      unread_by_role: has_unread_external ? latestExternalRole : null,
      unread_at: has_unread_external ? latestExternal : null,
    };
  });
}
