#!/usr/bin/env python3
"""Build FOG God Mode outputs from fog-data.json + dashboard.template.html.

Emits two things:
  1. fog-godmode.html            - standalone page (Claude artifact publishing; gitignored)
  2. ../../app/api/fog-analytics/dashboard-html.generated.ts
                                 - the SAME page wrapped as a full dark-theme HTML
                                   document, exported as a TS string so the OpsHub
                                   API route can serve it (bundles automatically,
                                   no filesystem tracing needed on Vercel).
"""
import json, pathlib

root = pathlib.Path(__file__).parent
data = json.dumps(json.load(open(root / "fog-data.json")), separators=(",", ":"))
data = data.replace("</", "<\\/")  # keep the inline <script> block intact
body = (root / "dashboard.template.html").read_text().replace("__DATA__", data)

(root / "fog-godmode.html").write_text(body)

# OpsHub app theme is dark; stamp data-theme so the embedded page matches
# regardless of the viewer's OS preference.
doc = (
    '<!doctype html><html data-theme="dark"><head><meta charset="utf-8">'
    '<meta name="viewport" content="width=device-width, initial-scale=1">'
    "</head><body>" + body + "</body></html>"
)
out = root.parent.parent / "app" / "api" / "fog-analytics" / "dashboard-html.generated.ts"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "// GENERATED by tools/fog-godmode/build.py - DO NOT EDIT.\n"
    "// Source: tools/fog-godmode/dashboard.template.html + fog-data.json\n"
    "export const FOG_DASHBOARD_HTML: string = " + json.dumps(doc) + ";\n"
)
print("wrote fog-godmode.html", len(body) // 1024, "KB")
print("wrote", out.relative_to(root.parent.parent), len(doc) // 1024, "KB")
